// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyeMnc0gKhW33rsMUfaWgieAVYnuycIeU',
    appId: '1:878169348187:web:d60d5f51d197b7ea39877e',
    messagingSenderId: '878169348187',
    projectId: 'wisespend-ae50c',
    authDomain: 'wisespend-ae50c.firebaseapp.com',
    storageBucket: 'wisespend-ae50c.firebasestorage.app',
    measurementId: 'G-ENDV492XET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSkh85EH-kGrZfQbFdWWPl-Tpg2kQoEA',
    appId: '1:878169348187:android:2a1bf8cf3042a09039877e',
    messagingSenderId: '878169348187',
    projectId: 'wisespend-ae50c',
    storageBucket: 'wisespend-ae50c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnQtDWLjKTIPbUbeGQOLOiYu370S1Qyts',
    appId: '1:878169348187:ios:73d7879b0c76de9339877e',
    messagingSenderId: '878169348187',
    projectId: 'wisespend-ae50c',
    storageBucket: 'wisespend-ae50c.firebasestorage.app',
    iosBundleId: 'com.example.wiseSpendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnQtDWLjKTIPbUbeGQOLOiYu370S1Qyts',
    appId: '1:878169348187:ios:73d7879b0c76de9339877e',
    messagingSenderId: '878169348187',
    projectId: 'wisespend-ae50c',
    storageBucket: 'wisespend-ae50c.firebasestorage.app',
    iosBundleId: 'com.example.wiseSpendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyeMnc0gKhW33rsMUfaWgieAVYnuycIeU',
    appId: '1:878169348187:web:2dd7d12800501be039877e',
    messagingSenderId: '878169348187',
    projectId: 'wisespend-ae50c',
    authDomain: 'wisespend-ae50c.firebaseapp.com',
    storageBucket: 'wisespend-ae50c.firebasestorage.app',
    measurementId: 'G-NRF6FK4FDX',
  );
}
